server:
  port: 8086
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/employee?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    serialization:
      indent_output: true

  # 设置mybatis 的别名（指定包下的类名既别名）
mybatis:
  type-aliases-package: com.springboot.bank.domain
  mapper-locations: mybatis/mapper/*.xml

logging:
  level:
    org.springframework.security: info

# JWT
jwt:
  header:  Authorization
  secret:  mySecret
# token
  expiration:  604800
  tokenHead:  Bearer
  router:
    authentication:
      path: auth
      refresh: refresh